#include<stdio.h>
#define TRANSMIT_SIZE 8
#define DATA_SIZE 38
#define SAVE_SIZE 24

int main( int argc, char **argv ) {
  int x, y, nrows, p;
  char tipo;
  FILE *fout;

  // lendo argumentos
  if ( argc != 3 ) {
    printf( "Uso: ifp_set nrows saida.\n" );
    return 0;
  }
  sscanf( argv[ 1 ], "%d", &nrows );
  fout = fopen( argv[ 2 ], "w" );

  // imprimindo início do código

  fprintf( fout, "/***********************************/\n");
  fprintf( fout, "// INCLUDES\n");
  fprintf( fout, "/***********************************/\n");
  fprintf( fout, "`include \"ifp.v\"\n");
  fprintf( fout, "module ifp_set(\n" );
  fprintf( fout, "  clock,\n" );
  fprintf( fout, "  AVL_chipselect,\n" );
  fprintf( fout, "  AVL_write,\n" );
  fprintf( fout, "  AVL_address,\n" );
  fprintf( fout, "  AVL_writedata,\n" );
  fprintf( fout, "  AVL_readdata,\n" );
  fprintf( fout, "  SC_read,\n" );
  fprintf( fout, "  SC_send,\n" );
  fprintf( fout, "  SC_receive,\n" );
  fprintf( fout, "  SC_write,\n" );
  fprintf( fout, "  SC_run,\n" );
  fprintf( fout, "  SC_address,\n" );
  fprintf( fout, "  SC_pathfunction,\n" );
  fprintf( fout, "  SC_neighborhood,\n" );
  fprintf( fout, "  SC_neighbor_address,\n" );
  fprintf( fout, "  SC_data_type,\n" );
  fprintf( fout, "  SC_carry_in,\n" );
  fprintf( fout, "  SM_state,\n" );
  fprintf( fout, "  SM_direction,\n" );
  fprintf( fout, "  IFPS_direction,\n" );
  fprintf( fout, "  IFPS_finish\n" );
  fprintf( fout, ");\n" );
  fprintf( fout, "\n" );
  fprintf( fout, "  // primitive parameters\n" );
  fprintf( fout, "  parameter IFP_LINE = %d;\n", nrows );
  fprintf( fout, "  parameter SECTOR_LINE = 3;\n" );
  fprintf( fout, "  parameter SECTOR_BITS = 2;\n" );
  fprintf( fout, "  parameter NIL = 1024'hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;\n" );
  fprintf( fout, "  parameter ZERO = 1024'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;\n" );
  fprintf( fout, "  parameter TRANSMIT_SIZE = 8;\n" );
  fprintf( fout, "  parameter SAVE_SIZE = 24;\n" );
  fprintf( fout, "  parameter DATA_SIZE = 38;\n" );
  fprintf( fout, "  parameter STOP_ST = 2'h0;\n" );
  fprintf( fout, "  parameter COST_ST = 2'h1;\n" );
  fprintf( fout, "  parameter ROOT_ST = 2'h2;\n" );
  fprintf( fout, "  parameter SAVE_ST = 2'h3;\n" );
  fprintf( fout, "\n" );
  fprintf( fout, "  // devived parameters\n" );
  fprintf( fout, "  parameter ADDR_SIZE = 2 * ( SECTOR_BITS + 6 );\n" );
  fprintf( fout, "  parameter MEM_SIZE = DATA_SIZE * SECTOR_LINE * SECTOR_LINE;\n" );
  fprintf( fout, "\n" );
  fprintf( fout, "  // global signals\n" );
  fprintf( fout, "  input clock;\n" );
  fprintf( fout, "  // avalon signals\n" );
  fprintf( fout, "  input AVL_chipselect;\n" );
  fprintf( fout, "  input AVL_write;\n" );
  fprintf( fout, "  input AVL_address;\n" );
  fprintf( fout, "  input [ 31 : 0 ] AVL_writedata;\n" );
  fprintf( fout, "  output [ 31 : 0 ] AVL_readdata;\n" );
  fprintf( fout, "  // SC signals\n" );
  fprintf( fout, "  input SC_write;\n" );
  fprintf( fout, "  input SC_read;\n" );
  fprintf( fout, "  input SC_send;\n" );
  fprintf( fout, "  input SC_receive;\n" );
  fprintf( fout, "  input SC_run;\n" );
  fprintf( fout, "  input [ ADDR_SIZE - 1 : 0 ] SC_address;\n" );
  fprintf( fout, "  input [ 1 : 0 ] SC_pathfunction;\n" );
  fprintf( fout, "  input SC_neighborhood;\n" );
  fprintf( fout, "  input SC_data_type;\n" );
  fprintf( fout, "  input SC_carry_in;\n" );
  fprintf( fout, "  input SC_neighbor_address;\n" );
  fprintf( fout, "   // SM  signals\n" );
  fprintf( fout, "  input [ 1 : 0 ] SM_state;\n" );
  fprintf( fout, "  input [ 2 : 0 ] SM_direction;\n" );
  fprintf( fout, "  // IFP set signals\n" );
  fprintf( fout, "  input IFPS_direction;\n" );
  fprintf( fout, "  output IFPS_finish;\n" );
  fprintf( fout, "\n" );
  fprintf( fout, "  // registers\n" );
  if ( ( nrows * nrows ) % 32 != 0 ) fprintf( fout, "  reg [ IFP_LINE * IFP_LINE + %d - 1 : 0 ] ri;\n", 32 - ( ( nrows * nrows ) % 32 ) );
  else fprintf( fout, "  reg [ IFP_LINE * IFP_LINE - 1 : 0 ] ri;\n" );
  fprintf( fout, "  reg [ IFP_LINE - 3 : 0 ] left_rg_in; // boarder input registers for comunication between sectors\n" );
  fprintf( fout, "  reg [ IFP_LINE - 3 : 0 ] right_rg_in; // boarder input registers for comunication between sectors\n" );
  fprintf( fout, "  reg [ IFP_LINE - 3 : 0 ] up_rg_in; // boarder input registers for comunication between sectors\n" );
  fprintf( fout, "  reg [ IFP_LINE - 3 : 0 ] down_rg_in; // boarder input registers for comunication between sectors\n" );
  fprintf( fout, "  reg up_left_rg_in; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg up_right_rg_in; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg down_left_rg_in; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg down_right_rg_in; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg [ IFP_LINE - 3 : 0 ] left_propagate;\n" );
  fprintf( fout, "  reg [ IFP_LINE - 3 : 0 ] right_propagate;\n" );
  fprintf( fout, "  reg [ IFP_LINE - 3 : 0 ] up_propagate;\n" );
  fprintf( fout, "  reg [ IFP_LINE - 3 : 0 ] down_propagate;\n" );
  fprintf( fout, "  reg up_left_propagate;\n" );
  fprintf( fout, "  reg up_right_propagate;\n" );
  fprintf( fout, "  reg down_left_propagate;\n" );
  fprintf( fout, "  reg down_right_propagate;\n" );
  fprintf( fout, "  reg [ 1 : 0 ] SM_state_rg; // to work with IFP's state.\n" );
  fprintf( fout, "  reg [ 2 : 0 ] SM_direction_rg; // to work with IFP's state.\n" );
  fprintf( fout, "  reg SC_neighborhood_rg;\n" );
  fprintf( fout, "  reg SC_read_rg;\n" );
  fprintf( fout, "  reg SC_write_rg;\n" );
  fprintf( fout, "  reg SC_receive_rg;\n" );
  fprintf( fout, "  reg SC_send_rg;\n" );
  fprintf( fout, "  reg SC_run_rg;\n" );
  fprintf( fout, "  reg SC_data_type_rg;\n" );
  fprintf( fout, "  reg AVL_chipselect_rg;\n" );
  fprintf( fout, "  reg AVL_write_rg;\n" );
  fprintf( fout, "  reg AVL_address_rg;\n" );
  fprintf( fout, "  reg SC_neighbor_address_rg;\n" );
  fprintf( fout, "  reg [ 31 : 0 ] AVL_writedata_rg;\n" );
  fprintf( fout, "\n" );
  fprintf( fout, "  // linkage signals\n" );
  fprintf( fout, "  wire AVL_write_memory;\n" );
  fprintf( fout, "  wire AVL_read_memory;\n" );
  fprintf( fout, "  reg [ IFP_LINE * IFP_LINE - 1 : 0 ] IFPS_data_in_bl;\n" );
  fprintf( fout, "  reg [ IFP_LINE * IFP_LINE - 1 : 0 ] IFPS_extern_data_in_bl;\n" );
  fprintf( fout, "  reg [ IFP_LINE * IFP_LINE - 1 : 0 ] IFPS_intern_data_in_bl;\n" );
  fprintf( fout, "  wire [ IFP_LINE * IFP_LINE - 1 : 0 ] IFPS_data_out_bl;\n" );
  fprintf( fout, "\n" );
  fprintf( fout, "  // auxiliar\n" );
  fprintf( fout, "  integer ifp_l, ifp_c;\n" );
  fprintf( fout, "\n" );
  fprintf( fout, "  reg [ ( IFP_LINE - 2 ) * ( IFP_LINE - 2 ) - 1 : 0 ] central_rg_out;\n" );
  fprintf( fout, "  reg [ IFP_LINE - 3 : 0 ] left_rg_out; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg [ IFP_LINE - 3 : 0 ] right_rg_out; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg [ IFP_LINE - 3 : 0 ] up_rg_out; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg [ IFP_LINE - 3 : 0 ] down_rg_out; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg up_left_rg_out; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg up_right_rg_out; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg down_left_rg_out; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg down_right_rg_out; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "\n" );
  fprintf( fout, "  reg [ ( IFP_LINE - 2 ) * ( IFP_LINE - 2 ) - 1 : 0 ] central_mem_in;\n" );
  fprintf( fout, "  reg [ IFP_LINE - 3 : 0 ] left_mem_in; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg [ IFP_LINE - 3 : 0 ] right_mem_in; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg [ IFP_LINE - 3 : 0 ] up_mem_in; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg [ IFP_LINE - 3 : 0 ] down_mem_in; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg up_left_mem_in; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg up_right_mem_in; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg down_left_mem_in; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg down_right_mem_in; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "\n" );
  fprintf( fout, "  reg [ ADDR_SIZE - 1 : 0 ] central_mem_address;\n" );
  fprintf( fout, "  reg [ ADDR_SIZE - 1 : 0 ] left_mem_address; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg [ ADDR_SIZE - 1 : 0 ] right_mem_address; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg [ ADDR_SIZE - 1 : 0 ] up_mem_address; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg [ ADDR_SIZE - 1 : 0 ] down_mem_address; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg [ ADDR_SIZE - 1 : 0 ] up_left_mem_address; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg [ ADDR_SIZE - 1 : 0 ] up_right_mem_address; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg [ ADDR_SIZE - 1 : 0 ] down_left_mem_address; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg [ ADDR_SIZE - 1 : 0 ] down_right_mem_address; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "\n" );
  fprintf( fout, "//Controls wires\n" );
  fprintf( fout, "  wire mem_enable;\n" );
  fprintf( fout, "\n" );
  fprintf( fout, "  reg [ ( IFP_LINE - 2 ) * ( IFP_LINE - 2 ) - 1 : 0 ] central_mem_out;\n" );
  fprintf( fout, "  reg [ IFP_LINE - 3 : 0 ] left_mem_out; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg [ IFP_LINE - 3 : 0 ] right_mem_out; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg [ IFP_LINE - 3 : 0 ] up_mem_out; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg [ IFP_LINE - 3 : 0 ] down_mem_out; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg up_left_mem_out; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg up_right_mem_out; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg down_left_mem_out; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "  reg down_right_mem_out; // boarder output registers for comunication between sectors\n" );
  fprintf( fout, "\n" );

// tem relação com o numero de memorias e como elas se organizam.
  fprintf( fout, "  //Memories**********************\n" );
  fprintf( fout, "  reg[ ( IFP_LINE - 2 ) * ( IFP_LINE - 2 ) - 1 : 0 ] mem_central[ MEM_SIZE - 1 : 0 ];\n" );
  fprintf( fout, "  reg[ IFP_LINE - 3 : 0 ] mem_left[ MEM_SIZE - 1 : 0 ];\n" );
  fprintf( fout, "  reg[ IFP_LINE - 3 : 0 ] mem_right[ MEM_SIZE - 1 : 0 ];\n" );
  fprintf( fout, "  reg[ IFP_LINE - 3 : 0 ] mem_up[ MEM_SIZE - 1 : 0 ];\n" );
  fprintf( fout, "  reg[ IFP_LINE - 3 : 0 ] mem_down[ MEM_SIZE - 1 : 0 ];\n" );
  fprintf( fout, "  reg mem_up_left[ MEM_SIZE - 1 : 0 ];\n" );
  fprintf( fout, "  reg mem_up_right[ MEM_SIZE - 1 : 0 ];\n" );
  fprintf( fout, "  reg mem_down_left[ MEM_SIZE - 1 : 0 ];\n" );
  fprintf( fout, "  reg mem_down_right[ MEM_SIZE - 1 : 0 ];\n" );
  fprintf( fout, "\n" );

  // imprimindo código das ifps
  for( y = 0; y < nrows; y++ ) {//row
    for( x = 0; x < nrows; x++ ) {// col
      fprintf( fout, "    ifp U_ifp_%d_%d (\n", y, x );
      fprintf( fout, "      // global signals\n" );
      fprintf( fout, "      .clock( clock ),\n" );
      fprintf( fout, "      // SC signals\n" );
      fprintf( fout, "      .run( SC_run ),\n" );
      fprintf( fout, "      .mem_send( SC_send ),\n" );
      fprintf( fout, "      .mem_receive( SC_receive ),\n" );
      fprintf( fout, "      .pathfunction( SC_pathfunction ),\n" );
      fprintf( fout, "      .neighborhood( SC_neighborhood ),\n" );
      fprintf( fout, "      .carry_in( SC_carry_in ),\n" );
      fprintf( fout, "      .data_type( SC_data_type ),\n" );
      fprintf( fout, "      // SM signals\n" );
      fprintf( fout, "      .state( SM_state ),\n" );
      fprintf( fout, "      .direction( IFPS_direction ),\n" );
      fprintf( fout, "      // counter signals\n" );
      fprintf( fout, "      // neighbors signals\n" );
      if ( x == nrows - 1 ) fprintf( fout, "      .transmit_data_in( 1'b0 ),\n" );
      else fprintf( fout, "      .transmit_data_in( IFPS_data_out_bl[ %d * IFP_LINE + %d ] ),\n", y, x + 1 );
      fprintf( fout, "      // data_signals\n" );
      fprintf( fout, "      .data_in( IFPS_data_in_bl[ %d * IFP_LINE + %d ] ),\n", y, x );
      fprintf( fout, "      .data_out( IFPS_data_out_bl[ %d * IFP_LINE + %d ] )\n", y, x );
      fprintf( fout, "    );\n" );
      //fprintf( fout, "    defparam U_ifp_%d_%d.DATA_SIZE = DATA_SIZE;\n", y, x );
      fprintf( fout, "\n" );
    }
  }

  fprintf( fout, "  // assign auxiliar signals from AVL to IFPs\n" );
  fprintf( fout, "  assign AVL_write_memory = ( ( AVL_write_rg == 1'b1 ) && ( AVL_writedata_rg[ 1 : 0 ] == 2'b01 ) && ( AVL_address_rg == 1'b0 ) ) ? 1'b1 : 1'b0;\n" );
  fprintf( fout, "  assign AVL_read_memory = ( ( AVL_write_rg == 1'b1 ) && ( AVL_writedata_rg[ 1 : 0 ] == 2'b00 ) && ( AVL_address_rg == 1'b0 ) ) ? 1'b1 : 1'b0;\n" );
  fprintf( fout, "\n" );

  fprintf( fout, "  // assign of ri\n" );
  fprintf( fout, "  always@( posedge clock ) begin\n" );
  fprintf( fout, "    // IFTs read command\n" );
  fprintf( fout, "    if ( AVL_read_memory == 1 ) begin\n" );
  fprintf( fout, "      for ( ifp_l = 0; ifp_l < IFP_LINE - 2; ifp_l = ifp_l + 1 ) begin\n" );
  fprintf( fout, "        for ( ifp_c = 0; ifp_c < IFP_LINE - 2; ifp_c = ifp_c + 1 ) begin\n" );
  fprintf( fout, "          ri[ ( ifp_l + 1 ) * %d + 1 + ifp_c ] <= central_mem_out[ ifp_c + ifp_l * %d ];\n", nrows, nrows - 2 );
  fprintf( fout, "        end\n" );
  fprintf( fout, "        ri[ ( ifp_l + 1 ) * IFP_LINE ] <= left_mem_out[ ifp_l ];\n" );
  fprintf( fout, "        ri[ ( ifp_l + 2 ) * IFP_LINE - 1 ] <= right_mem_out[ ifp_l ];\n" );
  fprintf( fout, "        ri[ ifp_l + 1 ] <= up_mem_out[ ifp_l ];\n" );
  fprintf( fout, "        ri[ ifp_l + IFP_LINE * ( IFP_LINE - 1 ) + 1 ] <= down_mem_out[ ifp_l ];\n" );
  fprintf( fout, "      end\n" );
  fprintf( fout, "      ri[ 0 ] <= up_left_mem_out;\n" );
  fprintf( fout, "      ri[ IFP_LINE - 1 ] <= up_right_mem_out;\n" );
  fprintf( fout, "      ri[ IFP_LINE * ( IFP_LINE - 1 ) ] <= down_left_mem_out;\n" );
  fprintf( fout, "      ri[ IFP_LINE * IFP_LINE - 1 ] <= down_right_mem_out;\n" );
  fprintf( fout, "    end \n" );
  fprintf( fout, "    // DATA read/write command\n" );
  fprintf( fout, "    else if ( ( AVL_chipselect_rg == 1 ) && ( AVL_address_rg == 1 ) ) begin\n" );
  for( y = 0; y < ( nrows * nrows - 1 ) / 32; y++ ) {
    fprintf( fout, "      ri[ %d : %d ] <= ri[ %d : %d ];\n", y * 32 + 31, y * 32, ( y + 1 ) * 32 + 31, ( y + 1 ) * 32 );
  }
  if ( ( nrows * nrows ) % 32 != 0 ) fprintf( fout, "      ri[ %d : %d ] <= AVL_writedata[ 31 : 0 ];\n", nrows * nrows + ( 32 - ( ( nrows * nrows ) % 32 ) ) - 1, nrows * nrows + ( 32 - ( ( nrows * nrows ) % 32 ) ) - 32 );
  else fprintf( fout, "      ri[ %d : %d ] <= AVL_writedata[ 31 : 0 ];\n", nrows * nrows - 1, nrows * nrows - 32 );
  fprintf( fout, "    end \n" );
  fprintf( fout, "  end\n" );
  fprintf( fout, "\n" );

  fprintf( fout, "  // memories address assignment\n" );
  fprintf( fout, "  always@( posedge clock ) begin\n" );
  fprintf( fout, "    central_mem_address <= SC_address;\n" );
  fprintf( fout, "    // iqual to central_mem_address when AVL write and before receive internal_data \n" );
  fprintf( fout, "    if ( SC_neighbor_address_rg == 1'b0 ) begin\n" );
  fprintf( fout, "      left_mem_address <= SC_address;\n" );
  fprintf( fout, "      right_mem_address <= SC_address;\n" );
  fprintf( fout, "      up_mem_address <= SC_address;\n" );
  fprintf( fout, "      down_mem_address <= SC_address;\n" );
  fprintf( fout, "      up_left_mem_address <= SC_address;\n" );
  fprintf( fout, "      up_right_mem_address <= SC_address;\n" );
  fprintf( fout, "      down_left_mem_address <= SC_address;\n" );
  fprintf( fout, "      down_right_mem_address <= SC_address;\n" );
  fprintf( fout, "    end\n" );
  fprintf( fout, "    // get neighbor sectors to propagate \n" );
  fprintf( fout, "    else begin\n" );
  fprintf( fout, "      left_mem_address <= SC_address + DATA_SIZE;\n" );
  fprintf( fout, "      right_mem_address <= SC_address - DATA_SIZE;\n" );
  fprintf( fout, "      up_mem_address <= SC_address + DATA_SIZE * SECTOR_LINE;\n" );
  fprintf( fout, "      down_mem_address <= SC_address - DATA_SIZE * SECTOR_LINE;\n" );
  fprintf( fout, "      if ( SM_direction_rg[ 2 : 0 ] == 3'h0 ) begin\n" );
  fprintf( fout, "        up_left_mem_address <= SC_address + DATA_SIZE * SECTOR_LINE;\n" );
  fprintf( fout, "        up_right_mem_address <= SC_address + DATA_SIZE * SECTOR_LINE - DATA_SIZE;\n" );
  fprintf( fout, "        down_right_mem_address <= SC_address - DATA_SIZE;\n" );
  fprintf( fout, "      end\n" );
  fprintf( fout, "      if ( SM_direction_rg[ 2 : 0 ] == 3'h1 ) begin\n" );
  fprintf( fout, "        up_right_mem_address <= SC_address - DATA_SIZE;\n" );
  fprintf( fout, "        down_right_mem_address <= SC_address - DATA_SIZE;\n" );
  fprintf( fout, "      end\n" );
  fprintf( fout, "      if ( SM_direction_rg[ 2 : 0 ] == 3'h2 ) begin\n" );
  fprintf( fout, "        up_right_mem_address <= SC_address - DATA_SIZE;\n" );
  fprintf( fout, "        down_left_mem_address <= SC_address - DATA_SIZE * SECTOR_LINE;\n" );
  fprintf( fout, "        down_right_mem_address <= SC_address - DATA_SIZE * SECTOR_LINE - DATA_SIZE;\n" );
  fprintf( fout, "      end\n" );
  fprintf( fout, "      if ( SM_direction_rg[ 2 : 0 ] == 3'h3 ) begin\n" );
  fprintf( fout, "        down_left_mem_address <= SC_address - DATA_SIZE * SECTOR_LINE;\n" );
  fprintf( fout, "        down_right_mem_address <= SC_address - DATA_SIZE * SECTOR_LINE;\n" );
  fprintf( fout, "      end\n" );
  fprintf( fout, "      if ( SM_direction_rg[ 2 : 0 ] == 3'h4 ) begin\n" );
  fprintf( fout, "        up_left_mem_address <= SC_address + DATA_SIZE;\n" );
  fprintf( fout, "        down_left_mem_address <= SC_address - DATA_SIZE * SECTOR_LINE + DATA_SIZE;\n" );
  fprintf( fout, "        down_right_mem_address <= SC_address - DATA_SIZE * SECTOR_LINE;\n" );
  fprintf( fout, "      end\n" );
  fprintf( fout, "      if ( SM_direction_rg[ 2 : 0 ] == 3'h5 ) begin\n" );
  fprintf( fout, "        up_left_mem_address <= SC_address + DATA_SIZE;\n" );
  fprintf( fout, "        down_left_mem_address <= SC_address + DATA_SIZE;\n" );
  fprintf( fout, "      end\n" );
  fprintf( fout, "      if ( SM_direction_rg[ 2 : 0 ] == 3'h6 ) begin\n" );
  fprintf( fout, "        up_left_mem_address <= SC_address + DATA_SIZE * SECTOR_LINE + DATA_SIZE;\n" );
  fprintf( fout, "        up_right_mem_address <= SC_address + DATA_SIZE * SECTOR_LINE;\n" );
  fprintf( fout, "        down_left_mem_address <= SC_address + DATA_SIZE;\n" );
  fprintf( fout, "      end\n" );
  fprintf( fout, "      if ( SM_direction_rg[ 2 : 0 ] == 3'h7 ) begin\n" );
  fprintf( fout, "        up_left_mem_address <= SC_address + DATA_SIZE * SECTOR_LINE;\n" );
  fprintf( fout, "        up_right_mem_address <= SC_address + DATA_SIZE * SECTOR_LINE;\n" );
  fprintf( fout, "      end\n" );
  fprintf( fout, "    end\n" );
  fprintf( fout, "  end\n" );
  fprintf( fout, "\n" );

  fprintf( fout, "  assign mem_enable = ( SC_write_rg | AVL_write_memory == 1 ) ? 1'b1 : 1'b0;\n" );
  fprintf( fout, "\n" );

  fprintf( fout, "  // memories input regiesters assignment\n" );
  fprintf( fout, "  always@* begin\n" );
  fprintf( fout, "    if ( ( AVL_write_rg == 1'b1 ) && ( AVL_writedata_rg[ 1 ] == 1'b0 ) ) begin // reading from AVL\n" );
  fprintf( fout, "      for ( ifp_l = 0; ifp_l < IFP_LINE - 2; ifp_l = ifp_l + 1 ) begin\n" );
  fprintf( fout, "        for ( ifp_c = 0; ifp_c < IFP_LINE - 2; ifp_c = ifp_c + 1 ) begin\n" );
  fprintf( fout, "          central_mem_in[ ifp_c + ifp_l * %d ] <= ri[ ( ifp_l + 1 ) * %d + 1 + ifp_c ];\n", nrows - 2, nrows );
  fprintf( fout, "        end\n" );
  fprintf( fout, "        left_mem_in[ ifp_l ] <= ri[ ( ifp_l + 1 ) * IFP_LINE ];\n" );
  fprintf( fout, "        right_mem_in[ ifp_l ] <= ri[ ( ifp_l + 2 ) * IFP_LINE - 1 ];\n" );
  fprintf( fout, "        up_mem_in[ ifp_l ] <= ri[ ifp_l + 1 ];\n" );
  fprintf( fout, "        down_mem_in[ ifp_l ] <= ri[ ifp_l + IFP_LINE * ( IFP_LINE - 1 ) + 1 ];\n" );
  fprintf( fout, "      end\n" );
  fprintf( fout, "      up_left_mem_in <= ri[ 0 ];\n" );
  fprintf( fout, "      up_right_mem_in <= ri[ IFP_LINE - 1 ];\n" );
  fprintf( fout, "      down_left_mem_in <= ri[ IFP_LINE * ( IFP_LINE - 1 ) ];\n" );
  fprintf( fout, "      down_right_mem_in <= ri[ IFP_LINE * IFP_LINE - 1 ];\n" );
  fprintf( fout, "    end\n" );
  fprintf( fout, "    else begin // reading from IFP'S\n" );
  fprintf( fout, "      central_mem_in <= central_rg_out;\n" );
  fprintf( fout, "      left_mem_in <= left_rg_out;\n" );
  fprintf( fout, "      right_mem_in <= right_rg_out;\n" );
  fprintf( fout, "      up_mem_in <= up_rg_out;\n" );
  fprintf( fout, "      down_mem_in <= down_rg_out;\n" );
  fprintf( fout, "      up_left_mem_in <= up_left_rg_out;\n" );
  fprintf( fout, "      up_right_mem_in <= up_right_rg_out;\n" );
  fprintf( fout, "      down_left_mem_in <= down_left_rg_out;\n" );
  fprintf( fout, "      down_right_mem_in <= down_right_rg_out;\n" );
  fprintf( fout, "    end\n" );
  fprintf( fout, "  end\n" );
  fprintf( fout, "\n" );

  fprintf( fout, "  always@( posedge clock ) begin\n" );
  fprintf( fout, "    if ( mem_enable == 1 ) begin\n" );
  fprintf( fout, "      mem_central[ central_mem_address ] <= central_mem_in;\n" );
  fprintf( fout, "      mem_left[ left_mem_address ] <= left_mem_in;\n" );
  fprintf( fout, "      mem_right[ right_mem_address ] <= right_mem_in;\n" );
  fprintf( fout, "      mem_up[ up_mem_address ] <= up_mem_in;\n" );
  fprintf( fout, "      mem_down[ down_mem_address ] <= down_mem_in;\n" );
  fprintf( fout, "      mem_up_left[ up_left_mem_address ] <= up_left_mem_in;\n" );
  fprintf( fout, "      mem_up_right[ up_right_mem_address ] <= up_right_mem_in;\n" );
  fprintf( fout, "      mem_down_left[ down_left_mem_address ] <= down_left_mem_in;\n" );
  fprintf( fout, "      mem_down_right[ down_right_mem_address ] <= down_right_mem_in;\n" );
  fprintf( fout, "    end\n" );
  fprintf( fout, "    central_mem_out <= mem_central[ central_mem_address ];\n" );
  fprintf( fout, "    left_mem_out <= mem_left[ left_mem_address ];\n" );
  fprintf( fout, "    right_mem_out <= mem_right[ right_mem_address ];\n" );
  fprintf( fout, "    up_mem_out <= mem_up[ up_mem_address ];\n" );
  fprintf( fout, "    down_mem_out <= mem_down[ down_mem_address ];\n" );
  fprintf( fout, "    up_left_mem_out <= mem_up_left[ up_left_mem_address ];\n" );
  fprintf( fout, "    up_right_mem_out <= mem_up_right[ up_right_mem_address ];\n" );
  fprintf( fout, "    down_left_mem_out <= mem_down_left[ down_left_mem_address ];\n" );
  fprintf( fout, "    down_right_mem_out <= mem_down_right[ down_right_mem_address ];\n" );
  fprintf( fout, "  end\n" );
  fprintf( fout, "\n" );

  fprintf( fout, "  //assign propagation registers from borders\n" );
  fprintf( fout, "  always@( posedge clock ) begin\n" );
  fprintf( fout, "    if ( ( SC_run_rg == 1'b1 ) && ( SM_state_rg == STOP_ST ) ) begin // write to IFPs\n" );
  fprintf( fout, "      for ( ifp_l = 0; ifp_l < IFP_LINE - 2; ifp_l = ifp_l + 1 ) begin\n" );
  fprintf( fout, "        if ( central_mem_address %% ( SECTOR_LINE * DATA_SIZE ) < DATA_SIZE ) left_propagate[ ifp_l ] <= 1'b0;\n" );
  fprintf( fout, "        else left_propagate[ ifp_l ] <= right_mem_out[ ifp_l ];\n" );
  fprintf( fout, "        if ( central_mem_address %% ( SECTOR_LINE * DATA_SIZE ) >= ( SECTOR_LINE - 1 ) * DATA_SIZE ) right_propagate[ ifp_l ] <= 1'b0;\n" );
  fprintf( fout, "        else right_propagate[ ifp_l ] <= left_mem_out[ ifp_l ];\n" );
  fprintf( fout, "        if ( central_mem_address < SECTOR_LINE * DATA_SIZE ) up_propagate[ ifp_l ] <= 1'b0;\n" );
  fprintf( fout, "        else up_propagate[ ifp_l ] <= down_mem_out[ ifp_l ];\n" );
  fprintf( fout, "        if ( central_mem_address >= ( SECTOR_LINE - 1 ) * SECTOR_LINE * DATA_SIZE ) down_propagate[ ifp_l ] <= 1'b0;\n" );
  fprintf( fout, "        else down_propagate[ ifp_l ] <= up_mem_out[ ifp_l ];\n" );
  fprintf( fout, "      end\n" );
  fprintf( fout, "      if ( ( ( central_mem_address %% ( SECTOR_LINE * DATA_SIZE ) >= DATA_SIZE ) && ( central_mem_address >= SECTOR_LINE * DATA_SIZE ) && " );
  fprintf( fout, "( SM_direction_rg[ 2 : 0 ] == 3'h2 ) ) || ( ( central_mem_address %% ( SECTOR_LINE * DATA_SIZE ) >= DATA_SIZE ) && ( SM_direction_rg[ 2 : 1 ] == 2'h0 ) " );
  fprintf( fout, ") || ( ( central_mem_address >= SECTOR_LINE * DATA_SIZE ) && ( ( SM_direction_rg[ 2 : 0 ] == 3'h3 ) || ( SM_direction_rg[ 2 : 0 ] == 3'h4 ) ) ) ) " );
  fprintf( fout, "up_left_propagate <= down_right_mem_out;\n" );
  fprintf( fout, "      else up_left_propagate <= 1'b0;\n" );
  fprintf( fout, "      if ( ( ( central_mem_address %% ( SECTOR_LINE * DATA_SIZE ) < ( SECTOR_LINE - 1 ) * DATA_SIZE ) && ( central_mem_address >= SECTOR_LINE * " );
  fprintf( fout, "DATA_SIZE ) && ( SM_direction_rg[ 2 : 0 ] == 3'h4 ) ) || ( ( central_mem_address %% ( SECTOR_LINE * DATA_SIZE ) < ( SECTOR_LINE - 1 ) * DATA_SIZE ) && " );
  fprintf( fout, " ( ( SM_direction_rg[ 2 : 0 ] == 3'h5 ) || ( SM_direction_rg[ 2 : 0 ] == 3'h6 ) ) ) || ( ( central_mem_address >= SECTOR_LINE * DATA_SIZE ) && ( ( SM_direction_rg[ 2 : 0 ] == 3'h2 ) || ( SM_direction_rg[ 2 : 0 ] == 3'h3 ) ) ) ) " );
  fprintf( fout, "up_right_propagate <= down_left_mem_out;\n" );
  fprintf( fout, "      else up_right_propagate <= 1'b0;\n" );
  fprintf( fout, "      if ( ( ( central_mem_address %% ( SECTOR_LINE * DATA_SIZE ) >= DATA_SIZE ) && ( central_mem_address < ( SECTOR_LINE - 1 ) * SECTOR_LINE * " );
  fprintf( fout, "DATA_SIZE ) && ( SM_direction_rg[ 2 : 0 ] == 3'h0 ) ) || ( ( central_mem_address %% ( SECTOR_LINE * DATA_SIZE ) >= DATA_SIZE ) && " );
  fprintf( fout, "( ( SM_direction_rg[ 2 : 0 ] == 3'h1 ) || ( SM_direction_rg[ 2 : 0 ] == 3'h2 ) ) ) || ( ( central_mem_address < ( SECTOR_LINE - 1 ) * SECTOR_LINE * DATA_SIZE ) && ( SM_direction_rg[ 2 : 1 ] == 2'h3 ) ) )" );
  fprintf( fout, "down_left_propagate <= up_right_mem_out;\n" );
  fprintf( fout, "      else down_left_propagate <= 1'b0;\n" );
  fprintf( fout, "      if ( ( ( central_mem_address %% ( SECTOR_LINE * DATA_SIZE ) < ( SECTOR_LINE - 1 ) * DATA_SIZE ) && ( central_mem_address < ( SECTOR_LINE - 1 ) * " );
  fprintf( fout, "SECTOR_LINE * DATA_SIZE ) && ( SM_direction_rg[ 2 : 0 ] == 3'h6 ) ) || ( ( central_mem_address %% ( SECTOR_LINE * DATA_SIZE ) < ( SECTOR_LINE - 1 ) * " );
  fprintf( fout, "DATA_SIZE ) &&  ( SM_direction_rg[ 2 : 1 ] == 2'h2 ) ) || ( ( central_mem_address < ( SECTOR_LINE - 1 ) * SECTOR_LINE * DATA_SIZE ) && " );
  fprintf( fout, "( ( SM_direction_rg[ 2 : 0 ] == 3'h7 ) || ( SM_direction_rg[ 2 : 0 ] == 3'h8 ) ) ) ) down_right_propagate <= up_left_mem_out;\n" );
  fprintf( fout, "      else down_right_propagate <= 1'b0;\n" );

  fprintf( fout, "    end\n" );
  fprintf( fout, "    else if ( SC_run_rg == 1'b0 ) begin \n" );
  fprintf( fout, "      left_propagate <= 0;\n" );
  fprintf( fout, "      right_propagate <= 0;\n" );
  fprintf( fout, "      up_propagate <= 0;\n" );
  fprintf( fout, "      down_propagate <= 0;\n" );
  fprintf( fout, "      up_left_propagate <= 1'b0;\n" );
  fprintf( fout, "      up_right_propagate <= 1'b0;\n" );
  fprintf( fout, "      down_left_propagate <= 1'b0;\n" );
  fprintf( fout, "      down_right_propagate <= 1'b0;\n" );
  fprintf( fout, "    end\n" );
  fprintf( fout, "  end\n" );
  fprintf( fout, "\n" );

  fprintf( fout, "  //assign correct data for propagation\n" );
  fprintf( fout, "  always@* begin\n" );
  fprintf( fout, "    left_rg_in <= ( ~left_propagate ) | right_mem_out;\n" );
  fprintf( fout, "    right_rg_in <= ( ~right_propagate ) | left_mem_out;\n" );
  fprintf( fout, "    up_rg_in <= ( ~up_propagate ) | down_mem_out;\n" );
  fprintf( fout, "    down_rg_in <= ( ~down_propagate ) | up_mem_out;\n" );
  fprintf( fout, "    up_left_rg_in <= ( ~up_left_propagate ) | down_right_mem_out;\n" );
  fprintf( fout, "    up_right_rg_in <= ( ~up_right_propagate ) | down_left_mem_out;\n" );
  fprintf( fout, "    down_left_rg_in <= ( ~down_left_propagate ) | up_right_mem_out;\n" );
  fprintf( fout, "    down_right_rg_in <= ( ~down_right_propagate ) | up_left_mem_out;\n" );
  fprintf( fout, "  end\n" );
  fprintf( fout, "\n" );

  fprintf( fout, "   // assign IFPS_external_total_data_in\n" );
  fprintf( fout, "  always@* begin\n" );
  fprintf( fout, "    for ( ifp_l = 0; ifp_l < IFP_LINE ; ifp_l = ifp_l + 1 ) begin\n" );
  fprintf( fout, "      for ( ifp_c = 0; ifp_c < IFP_LINE ; ifp_c = ifp_c + 1 ) begin\n" );
  fprintf( fout, "        if ( SM_direction_rg[ 2 : 0 ] == 3'h1 ) begin // left data in right propagation\n" ); // left data in right propagation
  fprintf( fout, "          if ( ( ifp_c == 0 ) && ( ifp_l == 0 ) ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= down_left_rg_in;\n" );
  fprintf( fout, "          else if ( ( ifp_c == 0 ) && ( ifp_l == IFP_LINE - 1 ) ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= up_left_rg_in;\n" );
  fprintf( fout, "          else if ( ifp_c == 0 ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= left_rg_in[ ifp_l - 1 ];\n" );
  fprintf( fout, "          else IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= IFPS_data_out_bl[ ifp_l * IFP_LINE + ifp_c - 1 ];\n" );
  fprintf( fout, "        end\n" );
  fprintf( fout, "        else if ( SM_direction_rg[ 2 : 0 ] == 3'h5 ) begin // right data in left propagation\n" ); // right data in left propagation
  fprintf( fout, "          if ( ( ifp_c == IFP_LINE - 1 ) && ( ifp_l == 0 ) ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= down_right_rg_in;\n" );
  fprintf( fout, "          else if ( ( ifp_c == IFP_LINE - 1 ) && ( ifp_l == IFP_LINE - 1 ) ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= up_right_rg_in;\n" );
  fprintf( fout, "          else if ( ifp_c == IFP_LINE - 1 ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= right_rg_in[ ifp_l - 1 ];\n" );
  fprintf( fout, "          else IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= IFPS_data_out_bl[ ifp_l * IFP_LINE + ifp_c + 1 ];\n" );
  fprintf( fout, "        end\n" );
  fprintf( fout, "        else if ( SM_direction_rg[ 2 : 0 ] == 3'h3 ) begin // up data in down propagation\n" ); // up data in down propagation
  fprintf( fout, "          if ( ( ifp_l == 0 ) && ( ifp_c == 0 ) ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= up_right_rg_in;\n" );
  fprintf( fout, "          else if ( ( ifp_l == 0 ) && ( ifp_c == IFP_LINE - 1 ) )  IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= up_left_rg_in;\n" );
  fprintf( fout, "          else if ( ifp_l == 0 ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= up_rg_in[ ifp_c - 1 ];\n" );
  fprintf( fout, "          else IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= IFPS_data_out_bl[ ( ifp_l - 1 ) * IFP_LINE + ifp_c ];\n" );
  fprintf( fout, "        end\n" );
  fprintf( fout, "        else if ( SM_direction_rg[ 2 : 0 ] == 3'h7 ) begin // down data in up propagation\n" ); // down data in up propagation
  fprintf( fout, "          if ( ( ifp_l == IFP_LINE - 1 ) && ( ifp_c == 0 ) ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= down_right_rg_in;\n" );
  fprintf( fout, "          else if ( ( ifp_l == IFP_LINE - 1 ) && ( ifp_c == IFP_LINE - 1 ) ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= down_left_rg_in;\n" );
  fprintf( fout, "          else if ( ifp_l == IFP_LINE - 1 ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= down_rg_in[ ifp_c - 1 ];\n" );
  fprintf( fout, "          else IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= IFPS_data_out_bl[ ( ifp_l + 1 ) * IFP_LINE + ifp_c ];\n" );
  fprintf( fout, "        end\n" );
  fprintf( fout, "        else if ( SM_direction_rg[ 2 : 0 ] == 3'h0 ) begin // down left data in up right propagation\n" ); // down left data in up right propagation
  fprintf( fout, "          if ( ( ifp_c == 0 ) && ( ifp_l == IFP_LINE - 1 ) ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= down_left_rg_in;\n" );
  fprintf( fout, "          else if ( ( ifp_c == 0 ) && ( ifp_l == IFP_LINE - 2 ) ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= up_left_rg_in;\n" );
  fprintf( fout, "          else if ( ( ifp_c == 1 ) && ( ifp_l == IFP_LINE - 1 ) ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= down_right_rg_in;\n" );
  fprintf( fout, "          else if ( ifp_c == 0 ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= left_rg_in[ ifp_l ];\n" );
  fprintf( fout, "          else if ( ifp_l == IFP_LINE - 1 ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= down_rg_in[ ifp_c - 2 ];\n" );
  fprintf( fout, "          else IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= IFPS_data_out_bl[ ( ifp_l + 1 ) * IFP_LINE + ifp_c - 1 ];\n" );
  fprintf( fout, "        end\n" );
  fprintf( fout, "        else if ( SM_direction_rg[ 2 : 0 ] == 3'h4 ) begin // up right data in down left propagation\n" ); // up right data in down left propagation
  fprintf( fout, "          if ( ( ifp_c == IFP_LINE - 1 ) && ( ifp_l == 0 ) ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= up_right_rg_in;\n" );
  fprintf( fout, "          else if ( ( ifp_c == IFP_LINE - 2 ) && ( ifp_l == 0 ) ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= up_left_rg_in;\n" );
  fprintf( fout, "          else if ( ( ifp_c == IFP_LINE - 1 ) && ( ifp_l == 1 ) ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= down_right_rg_in;\n" );
  fprintf( fout, "          else if ( ifp_c == IFP_LINE - 1 ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= right_rg_in[ ifp_l - 2 ];\n" );
  fprintf( fout, "          else if ( ifp_l == 0 ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= up_rg_in[ ifp_c ];\n" );
  fprintf( fout, "          else IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= IFPS_data_out_bl[ ( ifp_l - 1 ) * IFP_LINE + ifp_c + 1 ];\n" );
  fprintf( fout, "        end\n" );
  fprintf( fout, "        else if ( SM_direction_rg[ 2 : 0 ] == 3'h2 ) begin // up left data in down right propagation\n" ); // up left data in down right propagation
  fprintf( fout, "          if ( ( ifp_l == 0 ) && ( ifp_c == 0 ) ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= up_left_rg_in;\n" );
  fprintf( fout, "          else if ( ( ifp_l == 1 ) && ( ifp_c == 0 ) ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= down_left_rg_in;\n" );
  fprintf( fout, "          else if ( ( ifp_l == 0 ) && ( ifp_c == 1 ) ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= up_right_rg_in;\n" );
  fprintf( fout, "          else if ( ifp_l == 0 ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= up_rg_in[ ifp_c - 2 ];\n" );
  fprintf( fout, "          else if ( ifp_c == 0 ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= left_rg_in[ ifp_l - 2 ];\n" );
  fprintf( fout, "          else IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= IFPS_data_out_bl[ ( ifp_l - 1 ) * IFP_LINE + ifp_c - 1 ];\n" );
  fprintf( fout, "        end\n" );
  fprintf( fout, "        else begin // down right data in up left propagation\n" ); // down right data in up left propagation
  fprintf( fout, "          if ( ( ifp_l == IFP_LINE - 1 ) && ( ifp_c == IFP_LINE - 1 ) ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= down_right_rg_in;\n" );
  fprintf( fout, "          else if ( ( ifp_l == IFP_LINE - 2 ) && ( ifp_c == IFP_LINE - 1 ) ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= up_right_rg_in;\n" );
  fprintf( fout, "          else if ( ( ifp_l == IFP_LINE - 1 ) && ( ifp_c == IFP_LINE - 2 ) ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= down_left_rg_in;\n" );
  fprintf( fout, "          else if ( ifp_l == IFP_LINE - 1 ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= down_rg_in[ ifp_c ];\n" );
  fprintf( fout, "          else if ( ifp_c == IFP_LINE - 1 ) IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= right_rg_in[ ifp_l ];\n" );
  fprintf( fout, "          else IFPS_extern_data_in_bl[ ifp_l * IFP_LINE + ifp_c ] <= IFPS_data_out_bl[ ( ifp_l + 1 ) * IFP_LINE + ifp_c + 1 ];\n" );
  fprintf( fout, "        end\n" );
  fprintf( fout, "      end\n" );
  fprintf( fout, "    end\n" );
  fprintf( fout, "  end\n" );
  fprintf( fout, "\n" );

  fprintf( fout, "  // assign of IFPS_intern_data_in_bl\n" );
  fprintf( fout, "  always@( posedge clock ) begin\n" );
  fprintf( fout, "    // IFTs read command\n" );
  fprintf( fout, "    if ( SC_read_rg == 1'b1 ) begin\n");
  fprintf( fout, "      for ( ifp_l = 0; ifp_l < IFP_LINE ; ifp_l = ifp_l + 1 ) begin\n" );
  fprintf( fout, "        for ( ifp_c = 0; ifp_c < IFP_LINE ; ifp_c = ifp_c + 1 ) begin\n" );
  fprintf( fout, "          if ( ( ifp_c == IFP_LINE - 1 ) && ( ifp_l == IFP_LINE - 1 ) ) IFPS_intern_data_in_bl[ ifp_l * %d + ifp_c ] <= down_right_mem_out;\n", nrows );
  fprintf( fout, "          else if ( ( ifp_c == 0 ) && ( ifp_l == 0 ) ) IFPS_intern_data_in_bl[ ifp_l * %d + ifp_c ] <= up_left_mem_out;\n", nrows );
  fprintf( fout, "          else if ( ( ifp_c == 0 ) && ( ifp_l == IFP_LINE - 1 ) ) IFPS_intern_data_in_bl[ ifp_l * %d + ifp_c ] <= down_left_mem_out;\n", nrows );
  fprintf( fout, "          else if ( ( ifp_c == IFP_LINE - 1 ) && ( ifp_l == 0 ) ) IFPS_intern_data_in_bl[ ifp_l * %d + ifp_c ] <= up_right_mem_out;\n", nrows );
  fprintf( fout, "          else if ( ifp_l == IFP_LINE - 1 ) IFPS_intern_data_in_bl[ ifp_l * %d + ifp_c ] <= down_mem_out[ ifp_c - 1 ];\n", nrows );
  fprintf( fout, "          else if ( ifp_c == IFP_LINE - 1 ) IFPS_intern_data_in_bl[ ifp_l * %d + ifp_c ] <= right_mem_out[ ifp_l - 1 ];\n", nrows );
  fprintf( fout, "          else if ( ifp_l == 0 ) IFPS_intern_data_in_bl[ ifp_l * %d + ifp_c ] <= up_mem_out[ ifp_c - 1 ];\n", nrows );
  fprintf( fout, "          else if ( ifp_c == 0 ) IFPS_intern_data_in_bl[ ifp_l * %d + ifp_c ] <= left_mem_out[ ifp_l - 1 ];\n", nrows );
  fprintf( fout, "          else IFPS_intern_data_in_bl[ ifp_l * %d + ifp_c ] <= central_mem_out[ ( ifp_l - 1 ) * %d + ifp_c - 1 ];\n", nrows, nrows - 2 );
  fprintf( fout, "        end \n" );
  fprintf( fout, "      end \n" );
  fprintf( fout, "    end \n" );
  fprintf( fout, "  end \n" );
  fprintf( fout, "\n" );

  fprintf( fout, "  // assign of IFPS_data_in_bl\n" );
  fprintf( fout, "  always@* begin\n" );
  fprintf( fout, "    if ( SC_run_rg == 1'b1 ) begin\n");
  fprintf( fout, "      IFPS_data_in_bl <= IFPS_extern_data_in_bl;\n" );
  fprintf( fout, "    end \n" );
  fprintf( fout, "    else begin\n");
  fprintf( fout, "      IFPS_data_in_bl <= IFPS_intern_data_in_bl;\n" );
  fprintf( fout, "    end \n" );
  fprintf( fout, "  end \n" );
  fprintf( fout, "\n" );

  fprintf( fout, "  // Assign of register out from left, right up and down.\n" );
  fprintf( fout, "  always@( posedge clock ) begin\n" );
  fprintf( fout, "    if ( SC_receive_rg == 1'b1 ) begin\n" );
  fprintf( fout, "      for ( ifp_l = 0; ifp_l < IFP_LINE - 2; ifp_l = ifp_l + 1 ) begin\n" );
  fprintf( fout, "        for ( ifp_c = 0; ifp_c < IFP_LINE - 2; ifp_c = ifp_c + 1 ) begin\n" );
  fprintf( fout, "          central_rg_out[ ifp_c + ifp_l * %d ] <= IFPS_data_out_bl[ ( ifp_l + 1 ) * %d + ifp_c + 1 ];\n", nrows - 2, nrows );
  fprintf( fout, "        end\n" );
  fprintf( fout, "        left_rg_out[ ifp_l ] <= IFPS_data_out_bl[ ( ifp_l + 1 ) * IFP_LINE ];\n" );
  fprintf( fout, "        right_rg_out[ ifp_l ] <= IFPS_data_out_bl[ ( ifp_l + 2 ) * IFP_LINE - 1 ];\n" );
  fprintf( fout, "        up_rg_out[ ifp_l ] <= IFPS_data_out_bl[ ifp_l + 1 ];\n" );
  fprintf( fout, "        down_rg_out[ ifp_l ] <= IFPS_data_out_bl[ IFP_LINE * ( IFP_LINE - 1 ) + ifp_l + 1 ];\n" );
  fprintf( fout, "      end\n" );
  fprintf( fout, "      up_left_rg_out <= IFPS_data_out_bl[ 0 ];\n" );
  fprintf( fout, "      up_right_rg_out <= IFPS_data_out_bl[ IFP_LINE - 1 ];\n" );
  fprintf( fout, "      down_left_rg_out <= IFPS_data_out_bl[ IFP_LINE * ( IFP_LINE - 1 ) ];\n" );
  fprintf( fout, "      down_right_rg_out <= IFPS_data_out_bl[ IFP_LINE * IFP_LINE - 1 ];\n" );
  fprintf( fout, "    end\n" );
  fprintf( fout, "  end\n" );
  fprintf( fout, "\n" );

  fprintf( fout, "  // assign output of inc_counter for SC\n" );
  fprintf( fout, "  assign IFPS_finish = ( ( IFPS_data_out_bl[ IFP_LINE * IFP_LINE - 1 : 0 ] == ZERO[ IFP_LINE * IFP_LINE - 1 : 0 ] ) && ( SC_run_rg == 1'b1 ) ) ? 1'b1 : 1'b0;\n" );
  fprintf( fout, "\n" );

  fprintf( fout, "  // assign of data out\n" );
  fprintf( fout, "  assign AVL_readdata = ri[ 31 : 0 ];\n" );
  fprintf( fout, "\n" );

  fprintf( fout, "   // register basic signals from SM and SC\n" );
  fprintf( fout, "    always@( posedge clock ) begin\n" );
  fprintf( fout, "       SC_data_type_rg <= SC_data_type;\n" );
  fprintf( fout, "       SC_neighborhood_rg <= SC_neighborhood;\n" );
  fprintf( fout, "       SC_read_rg <= SC_read;\n" );
  fprintf( fout, "       SC_write_rg <= SC_write;\n" );
  fprintf( fout, "       SC_receive_rg <= SC_receive;\n" );
  fprintf( fout, "       SC_send_rg <= SC_send;\n" );
  fprintf( fout, "       SC_run_rg <= SC_run;\n" );
  fprintf( fout, "       SC_neighbor_address_rg <= SC_neighbor_address;\n" );
  fprintf( fout, "       SM_state_rg <= SM_state;\n" );
  fprintf( fout, "       SM_direction_rg <= SM_direction;\n" );
  fprintf( fout, "       AVL_chipselect_rg <= AVL_chipselect;\n" );
  fprintf( fout, "       AVL_write_rg <= AVL_write;\n" );
  fprintf( fout, "       AVL_address_rg <= AVL_address;\n" );
  fprintf( fout, "       AVL_writedata_rg <= AVL_writedata;\n" );
  fprintf( fout, "    end\n" );
  fprintf( fout, "\n" );

  fprintf( fout, "endmodule // ifp_set\n" );


  // finalizando
  fclose( fout );
  return 0;
}
